config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops
  # devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products

  resources :charges

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  get '/cart/tracking', to: 'orders#show', as: :tracking



  
  get 'welcome/home'
  root "welcome#home"
  get 'welcome/rest'
  get 'welcome/old'
  get 'welcome/auto'
  get 'welcome/electronics'
  get 'welcome/fashion'
  get 'welcome/gs'
  get 'welcome/grocery'
  get 'welcome/furniture'
  get 'welcome/health'
  get 'welcome/repair'
  get 'welcome/recent'
  get 'welcome/popular'
  get 'welcome/events'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/search'
  get 'welcome/decor'
  get 'welcome/sny'










  get 'welcome/shop1'
  get 'welcome/shop2'
  get 'welcome/shop3'
  get 'welcome/shop4'
  get 'welcome/shop5'
  get 'welcome/shop6'
  get 'welcome/shop7'
  get 'welcome/shop8'




















  get 'welcome/hbb1'
  get 'welcome/hbb2'
  get 'welcome/hbb3'
  get 'welcome/hbb4'
  get 'welcome/hbb5'
  get 'welcome/hbb6'
  get 'welcome/hbb7'
  get 'welcome/hbb8'
  get 'welcome/hbb9'
  get 'welcome/hbb10'
  get 'welcome/hbb11'
  get 'welcome/hbb12'
  get 'welcome/hbb13'
  get 'welcome/hbb14'
  get 'welcome/hbb15'
  get 'welcome/hbb16'
  get 'welcome/hbb17'
  get 'welcome/hbb18'
  get 'welcome/hbb19'
  get 'welcome/hbb20'
  get 'welcome/hbb21'
  get 'welcome/hbb22'
  get 'welcome/hbb23'
  get 'welcome/hbb24'
  get 'welcome/hbb25'
  get 'welcome/hbb26'
  get 'welcome/hbb27'
  get 'welcome/hbb28'
  get 'welcome/hbb29'
  get 'welcome/hbb30'
  get 'welcome/hbb31'
  get 'welcome/hbb32'
  get 'welcome/hbb33'
  get 'welcome/hbb34'
  get 'welcome/hbb35'
  get 'welcome/hbb36'
  get 'welcome/hbb37'
  get 'welcome/hbb38'
  get 'welcome/hbb39'
  get 'welcome/hbb40'
  get 'welcome/hbb41'
  get 'welcome/hbb42'
  get 'welcome/hbb43'
  get 'welcome/hbb44'
  get 'welcome/hbb45'
  get 'welcome/hbb46'
  get 'welcome/hbb47'
  get 'welcome/hbb48'
  get 'welcome/hbb49'
  get 'welcome/hbb50'
  get 'welcome/hbb51'
  get 'welcome/hbb52'
  get 'welcome/hbb53'
  get 'welcome/hbb54'
  get 'welcome/hbb55'
  get 'welcome/hbb56'
  get 'welcome/hbb57'
  get 'welcome/hbb58'
  get 'welcome/hbb59'
  get 'welcome/hbb60'
  get 'welcome/hbb61'
  get 'welcome/hbb62'
  get 'welcome/hbb63'
  get 'welcome/hbb64'
  get 'welcome/hbb65'
  get 'welcome/hbb66'
  get 'welcome/hbb67'
  get 'welcome/hbb68'
  get 'welcome/hbb69'






























  get 'welcome/fh1'
  get 'welcome/fh2'
  get 'welcome/fh3'
  get 'welcome/fh4'
  get 'welcome/fh5'
  get 'welcome/fh6'
  get 'welcome/fh7'
  get 'welcome/fh8'
  get 'welcome/fh9'
  get 'welcome/fh10'
  get 'welcome/fh11'
  get 'welcome/fh12'
  get 'welcome/fh13'
  get 'welcome/fh14'
  get 'welcome/fh15'
  get 'welcome/fh16'
  get 'welcome/fh17'
  get 'welcome/fh18'
  get 'welcome/fh19'
  get 'welcome/fh20'
  get 'welcome/fh21'
  get 'welcome/fh22'
  get 'welcome/fh23'
  get 'welcome/fh24'
  get 'welcome/fh25'
  get 'welcome/fh26'
  get 'welcome/fh27'
  get 'welcome/fh28'
  get 'welcome/fh29'
  get 'welcome/fh30'
  get 'welcome/fh31'
  get 'welcome/fh32'
  get 'welcome/fh33'
  get 'welcome/fh34'
  get 'welcome/fh35'
  get 'welcome/fh36'
  get 'welcome/fh37'
  get 'welcome/fh38'
  get 'welcome/fh39'
  get 'welcome/fh40'
  get 'welcome/fh41'
  get 'welcome/fh42'
  get 'welcome/fh43'
  get 'welcome/fh44'
  get 'welcome/fh45'
  get 'welcome/fh46'
  get 'welcome/fh47'
  get 'welcome/fh48'
  get 'welcome/fh49'
  get 'welcome/fh50'
  get 'welcome/fh51'
  get 'welcome/fh52'
  get 'welcome/fh53'
  get 'welcome/fh54'
  get 'welcome/fh55'
  get 'welcome/fh56'
  get 'welcome/fh57'
  get 'welcome/fh58'
  get 'welcome/fh59'
  get 'welcome/fh60'
  get 'welcome/fh61'
  get 'welcome/fh62'
  get 'welcome/fh63'
  get 'welcome/fh64'































  get 'welcome/fa1'
  get 'welcome/fa2'
  get 'welcome/fa3'
  get 'welcome/fa4'
  get 'welcome/fa5'
  get 'welcome/fa6'
  get 'welcome/fa7'
  get 'welcome/fa8'
  get 'welcome/fa9'
  get 'welcome/fa10'
  get 'welcome/fa11'
  get 'welcome/fa12'
  get 'welcome/fa13'
  get 'welcome/fa14'
  get 'welcome/fa15'
  get 'welcome/fa16'
  get 'welcome/fa17'
  get 'welcome/fa18'
  get 'welcome/fa19'
  get 'welcome/fa20'
  get 'welcome/fa21'
  get 'welcome/fa22'
  get 'welcome/fa23'
  get 'welcome/fa24'
  get 'welcome/fa25'
  get 'welcome/fa26'
  get 'welcome/fa27'
  get 'welcome/fa28'
  get 'welcome/fa29'
  get 'welcome/fa30'
  get 'welcome/fa31'
  get 'welcome/fa32'
  get 'welcome/fa33'
  get 'welcome/fa34'
  get 'welcome/fa35'
  get 'welcome/fa36'
  get 'welcome/fa37'
  get 'welcome/fa38'
  get 'welcome/fa39'
  get 'welcome/fa40'
  get 'welcome/fa41'
  get 'welcome/fa42'
  get 'welcome/fa43'
  get 'welcome/fa44'
  get 'welcome/fa45'
  get 'welcome/fa46'
  get 'welcome/fa47'
  get 'welcome/fa48'
  get 'welcome/fa49'
  get 'welcome/fa50'
  get 'welcome/fa51'
  get 'welcome/fa52'
  get 'welcome/fa53'
  get 'welcome/fa54'
  get 'welcome/fa55'
  get 'welcome/fa56'
  get 'welcome/fa57'
  get 'welcome/fa58'
  get 'welcome/fa59'
  get 'welcome/fa60'












































  get 'welcome/gv1'
  get 'welcome/gv2'
  get 'welcome/gv3'
  get 'welcome/gv4'
  get 'welcome/gv5'
  get 'welcome/gv6'
  get 'welcome/gv7'
  get 'welcome/gv8'
  get 'welcome/gv9'
  get 'welcome/gv10'
  get 'welcome/gv11'
  get 'welcome/gv12'
  get 'welcome/gv13'
  get 'welcome/gv14'
  get 'welcome/gv15'
  get 'welcome/gv16'
  get 'welcome/gv17'
  get 'welcome/gv18'
  get 'welcome/gv19'
  get 'welcome/gv20'
  get 'welcome/gv21'
  get 'welcome/gv22'
  get 'welcome/gv23'
  get 'welcome/gv24'
  get 'welcome/gv25'
  get 'welcome/gv26'
  get 'welcome/gv27'
  get 'welcome/gv28'
  get 'welcome/gv29'
  get 'welcome/gv30'
  get 'welcome/gv31'
  get 'welcome/gv32'
  get 'welcome/gv33'
  get 'welcome/gv34'
  get 'welcome/gv35'
  get 'welcome/gv36'
  get 'welcome/gv37'
  get 'welcome/gv38'
  get 'welcome/gv39'
  get 'welcome/gv40'
  get 'welcome/gv41'
  get 'welcome/gv42'























  get 'welcome/ea1'
  get 'welcome/ea2'
  get 'welcome/ea3'
  get 'welcome/ea4'
  get 'welcome/ea5'
  get 'welcome/ea6'
  get 'welcome/ea7'
  get 'welcome/ea8'
  get 'welcome/ea9'
  get 'welcome/ea10'
  get 'welcome/ea11'
  get 'welcome/ea12'
  get 'welcome/ea13'
  get 'welcome/ea14'
  get 'welcome/ea15'
  get 'welcome/ea16'
  get 'welcome/ea17'
  get 'welcome/ea18'


















  get 'welcome/te1'
  get 'welcome/te2'
  get 'welcome/te3'
  get 'welcome/te4'
  get 'welcome/te5'
  get 'welcome/te6'
  get 'welcome/te7'
  get 'welcome/te8'























  get 'welcome/do1'
  get 'welcome/do2'
  get 'welcome/do3'
  get 'welcome/do4'
  get 'welcome/do5'
  get 'welcome/do6'
  get 'welcome/do7'
  get 'welcome/do8'
  get 'welcome/do9'
  get 'welcome/do10'
  get 'welcome/do11'






















  get 'welcome/bt1'
  get 'welcome/bt2'
  get 'welcome/bt3'
  get 'welcome/bt4'
  get 'welcome/bt5'
  get 'welcome/bt6'

















  get 'welcome/sa1'
  get 'welcome/sa2'
  get 'welcome/sa3'
  get 'welcome/sa4'
  get 'welcome/sa5'





















  get 'welcome/hsr1'
  get 'welcome/hsr2'
  get 'welcome/hsr3'
  get 'welcome/hsr4'
  get 'welcome/hsr5'
  get 'welcome/hsr6'
  get 'welcome/hsr7'
  get 'welcome/hsr8'
  get 'welcome/hsr9'
  get 'welcome/hsr10'
  get 'welcome/hsr11'













  get 'welcome/ren1'
  get 'welcome/ren2'
  get 'welcome/ren3'
  get 'welcome/ren4'
  get 'welcome/ren5'
























  get 'welcome/hard1'
  get 'welcome/hard2'
  get 'welcome/hard3'
  get 'welcome/hard4'
  get 'welcome/hard5'
  get 'welcome/hard6'
  get 'welcome/hard7'
  get 'welcome/hard8'
  get 'welcome/hard9'
  get 'welcome/hard10'
  get 'welcome/hard11'
  get 'welcome/hard12'
  get 'welcome/hard13'
  get 'welcome/hard14'




















  get 'welcome/wed1'
  get 'welcome/wed2'
  get 'welcome/wed3'
  get 'welcome/wed4'
  get 'welcome/wed5'
  get 'welcome/wed6'
  get 'welcome/wed7'
  get 'welcome/wed8'
  get 'welcome/wed9'
  get 'welcome/wed10'
  get 'welcome/wed11'
  get 'welcome/wed12'
  get 'welcome/wed13'
  get 'welcome/wed14'
  get 'welcome/wed15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # new routes
  resources :registeration_numbers do
    resources :orders, controller: 'registeration_numbers/orders'
  end
  post :get_cities_by_state,       action: :get_cities_by_state, controller: :products
  post :get_areas_by_city,       action: :get_areas_by_city, controller: :products

   get "/users/auth/facebook", to: "users#sign_in"
   get "/users/auth/twitter", to: "users#sign_in"
   get "/users/auth/google_oauth2", to: "users#sign_in"
   devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" , sessions: "users/sessions"}

end

app/models/shop.rb
class Shop < ApplicationRecord
	mount_uploader :imageshop, ImageUploader
	belongs_to :user
	has_many :products
	belongs_to :registeration_number, required: false
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @products = Product.all
  end

  # GET /shops/new
  def new
    @shop = current_user.build_shop
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    if params[:shop][:registeration_number].present?
      code = RegisterationNumber.where(code: params[:shop][:registeration_number]).first
      if code.present?
        @shop = current_user.build_shop(shop_params)
        @shop.user = current_user
        @shop.registeration_number_id = code.id
        respond_to do |format|
          if @shop.save
            format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
            format.json { render :show, status: :created, location: @shop }
          else
            format.html { render :new }
            format.json { render json: @shop.errors, status: :unprocessable_entity }
          end
        end
      else    
        respond_to do |format|
          format.html { redirect_to new_shop_path, notice: 'Shop was successfully created.'  }
          format.json { render json: {registeration: "Registeration Number not foud"}, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to new_shop_path, notice: 'Shop was successfully created.'   }
        format.json { render json: {registeration: "Registeration Number not foud"}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :description, :imageshop, :location, :web, :email, :state, :city, :phone, :business, :category)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<style>
.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  color: #fff;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #fff;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  top: 0;
  right: 25px;
  font-size: 36px;

}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<div class="dark-bg sticky-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                            <span style="font-size:30px;cursor:pointer;" onclick="openNav()">&#9776; </span>
                            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/fashion">Fashion</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/electronics">Electronics</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/furniture">Furniture</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/kitchen">Kitchen</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/grocery">Grocery</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/restraunts">Retraunts</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/events">Events</a>
                                    </li>
                                    
                                   
                                    <% if user_signed_in? %>
                                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light top-btn" %></li>
                                    <% else %>
                                    <li><a href="/users/sign_in" class="btn btn-outline-light top-btn">SignUp/SignIn</a></li>
                                   <% end %>
                                </ul>
                            </div>
                            <li class="nav-item active">
                                        <a class="nav-link" href="/"><img src="/assets/search.png" style="width:30px; height:30px; margin-bottom:8px;"></a>
                                    </li>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
<body>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a class="navbar-brand" style="text-align:center;" href="/">NearClick</a>
  <br>
  <% if user_signed_in? %>
  <p style="text-align:center;">Welcome <%= current_user.username %></p>
  <% else %>
  <p style="text-align:center;">Welcome Guest</p>
  <% end %>
  <% if current_user&.shop %>
  <a href="/products/new">Add Product</a>
  <%= link_to 'Manage Shop', current_user.shop %>
  <% else %>
  <a href="#"><span>0</span> Your Cart</a>
  <a href="#">Wishlist</a>
  <% end %>
  <a href="/welcome/about">About</a>
  <a href="/welcome/contact">Contact</a>
</div>
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<div class="broke" style="text-align:center;">
<%= link_to 'Back', shops_path, class: "btn btn-danger" %>
</div>
 <footer class="main-block dark-bg" style="padding-bottom:30px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright &copy; 2019  Nearclick. All rights reserved. </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <ul>
                            <li><a href="#"><span class="ti-facebook"></span></a></li>
                            <li><a href="#"><span class="ti-twitter-alt"></span></a></li>
                            <li><a href="#"><span class="ti-instagram"></span></a></li>
                        </ul>

                        <ul>
                         <li class="nav-item active">
                                        <a class="nav-link" style="font-size:30px; font-weight:700; color:#ffffff" href="/welcome/about">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" style="font-size:30px; font-weight:700; color:#ffffff" href="/welcome/contact">Contact</a>
                                    </li>

                                </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

app/views/shops/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Imageshop</th>
      <th>Business type</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td><%= shop.imageshop %></td>
        <td><%= shop.business_type %></td>
        <td><%= shop.category %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<br>
<br>
<br>


<%= render 'form', shop: @shop %>

<div class="broke" style="text-align:center;">
<%= link_to 'Back', shops_path, class: "btn btn-danger" %>
</div>
 

app/views/shops/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<br>
<br>
<br>
<body>



    <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title" style="text-align:center;"><%= @shop.name %>'s Contact Info</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
         <h3><b>Location:</b></h3><br>
         <p><%= @shop.location %></p>
         <hr>

         <h3><b>Phone:</b></h3><br>
         <p><%= @shop.phone %></p>
         <hr>

         <h3><b>Website:</b></h3><br>
         <p><%= @shop.web %></p>
         <hr>

         <h3><b>Email:</b></h3><br>
         <p><%= @shop.email %></p>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>

  <div id="colorlib-page">

    <div id="colorlib-main">
      <div class="hero-wrap js-fullheight" style="background-image: url(/assets/bg_1.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="js-fullheight d-flex justify-content-center align-items-center">
          <div class="col-md-8 text text-center">
            <div class="img mb-4"><img src="<%= @shop.imageshop %>" style="width:150px; height:150px; border-radius: 50%;"></div>
            <div class="desc">
              <h2 class="subheading"><%= @shop.category %></h2>
              <h1 class="mb-4"><%= @shop.name %></h1>
              <p class="mb-4"><%= @shop.description %></p>
              <p class="btn-custom" data-toggle="modal" data-target="#myModal">Contact Shop </p>
              <% if current_user=(@shop.user) %>
<%= link_to 'Edit', edit_shop_path(@shop), class: 'btn btn-danger' %>
<% end %>
            </div>
          </div>
        </div>
      </div>
      <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-7 heading-section text-center">
            <h2 class="mb-4">Products</h2>
            <p>All the products listed here are directly sold by <%= @shop.name %> and NearClick is just there delivery partner, we deliver the product as it is without opening the package.</p>
          </div>
        </div>
        <div class="row">





              <% @shop.products.each do |product| %>

          <div class="col-md-4">
            <div class="blog-entry">
              <a href="#" class="img img-2"><img src="<%= product.image %>" style="width:300px; height:250px;"> </a>
              <div class="text text-2 pt-2 mt-3">
                <span class="category mb-3 d-block"><a href="#"><%= product.name %></a></span>
                <h3 class="mb-4"><a href="#"><%= product.category %></a></h3>
                <h3 class="mb-4"><a href="#">Rs: <%= product.price %></a></h3>
                <p class="mb-4"><%= product.description %></p>
                
                <div class="meta-wrap align-items-center">
                  
                  <div class="half">
                
                    <p><%= link_to "View Product", product, class: "btn btn-success" %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </section>

  </body>
</html>