config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops
  # devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products

  resources :charges

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  get '/cart/tracking', to: 'orders#show', as: :tracking



  
  get 'welcome/home'
  root "welcome#home"
  get 'welcome/rest'
  get 'welcome/old'
  get 'welcome/auto'
  get 'welcome/electronics'
  get 'welcome/fashion'
  get 'welcome/gs'
  get 'welcome/grocery'
  get 'welcome/furniture'
  get 'welcome/health'
  get 'welcome/repair'
  get 'welcome/recent'
  get 'welcome/popular'
  get 'welcome/events'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/search'
  get 'welcome/decor'
  get 'welcome/sny'










  get 'welcome/shop1'
  get 'welcome/shop2'
  get 'welcome/shop3'
  get 'welcome/shop4'
  get 'welcome/shop5'
  get 'welcome/shop6'
  get 'welcome/shop7'
  get 'welcome/shop8'




















  get 'welcome/hbb1'
  get 'welcome/hbb2'
  get 'welcome/hbb3'
  get 'welcome/hbb4'
  get 'welcome/hbb5'
  get 'welcome/hbb6'
  get 'welcome/hbb7'
  get 'welcome/hbb8'
  get 'welcome/hbb9'
  get 'welcome/hbb10'
  get 'welcome/hbb11'
  get 'welcome/hbb12'
  get 'welcome/hbb13'
  get 'welcome/hbb14'
  get 'welcome/hbb15'
  get 'welcome/hbb16'
  get 'welcome/hbb17'
  get 'welcome/hbb18'
  get 'welcome/hbb19'
  get 'welcome/hbb20'
  get 'welcome/hbb21'
  get 'welcome/hbb22'
  get 'welcome/hbb23'
  get 'welcome/hbb24'
  get 'welcome/hbb25'
  get 'welcome/hbb26'
  get 'welcome/hbb27'
  get 'welcome/hbb28'
  get 'welcome/hbb29'
  get 'welcome/hbb30'
  get 'welcome/hbb31'
  get 'welcome/hbb32'
  get 'welcome/hbb33'
  get 'welcome/hbb34'
  get 'welcome/hbb35'
  get 'welcome/hbb36'
  get 'welcome/hbb37'
  get 'welcome/hbb38'
  get 'welcome/hbb39'
  get 'welcome/hbb40'
  get 'welcome/hbb41'
  get 'welcome/hbb42'
  get 'welcome/hbb43'
  get 'welcome/hbb44'
  get 'welcome/hbb45'
  get 'welcome/hbb46'
  get 'welcome/hbb47'
  get 'welcome/hbb48'
  get 'welcome/hbb49'
  get 'welcome/hbb50'
  get 'welcome/hbb51'
  get 'welcome/hbb52'
  get 'welcome/hbb53'
  get 'welcome/hbb54'
  get 'welcome/hbb55'
  get 'welcome/hbb56'
  get 'welcome/hbb57'
  get 'welcome/hbb58'
  get 'welcome/hbb59'
  get 'welcome/hbb60'
  get 'welcome/hbb61'
  get 'welcome/hbb62'
  get 'welcome/hbb63'
  get 'welcome/hbb64'
  get 'welcome/hbb65'
  get 'welcome/hbb66'
  get 'welcome/hbb67'
  get 'welcome/hbb68'
  get 'welcome/hbb69'






























  get 'welcome/fh1'
  get 'welcome/fh2'
  get 'welcome/fh3'
  get 'welcome/fh4'
  get 'welcome/fh5'
  get 'welcome/fh6'
  get 'welcome/fh7'
  get 'welcome/fh8'
  get 'welcome/fh9'
  get 'welcome/fh10'
  get 'welcome/fh11'
  get 'welcome/fh12'
  get 'welcome/fh13'
  get 'welcome/fh14'
  get 'welcome/fh15'
  get 'welcome/fh16'
  get 'welcome/fh17'
  get 'welcome/fh18'
  get 'welcome/fh19'
  get 'welcome/fh20'
  get 'welcome/fh21'
  get 'welcome/fh22'
  get 'welcome/fh23'
  get 'welcome/fh24'
  get 'welcome/fh25'
  get 'welcome/fh26'
  get 'welcome/fh27'
  get 'welcome/fh28'
  get 'welcome/fh29'
  get 'welcome/fh30'
  get 'welcome/fh31'
  get 'welcome/fh32'
  get 'welcome/fh33'
  get 'welcome/fh34'
  get 'welcome/fh35'
  get 'welcome/fh36'
  get 'welcome/fh37'
  get 'welcome/fh38'
  get 'welcome/fh39'
  get 'welcome/fh40'
  get 'welcome/fh41'
  get 'welcome/fh42'
  get 'welcome/fh43'
  get 'welcome/fh44'
  get 'welcome/fh45'
  get 'welcome/fh46'
  get 'welcome/fh47'
  get 'welcome/fh48'
  get 'welcome/fh49'
  get 'welcome/fh50'
  get 'welcome/fh51'
  get 'welcome/fh52'
  get 'welcome/fh53'
  get 'welcome/fh54'
  get 'welcome/fh55'
  get 'welcome/fh56'
  get 'welcome/fh57'
  get 'welcome/fh58'
  get 'welcome/fh59'
  get 'welcome/fh60'
  get 'welcome/fh61'
  get 'welcome/fh62'
  get 'welcome/fh63'
  get 'welcome/fh64'































  get 'welcome/fa1'
  get 'welcome/fa2'
  get 'welcome/fa3'
  get 'welcome/fa4'
  get 'welcome/fa5'
  get 'welcome/fa6'
  get 'welcome/fa7'
  get 'welcome/fa8'
  get 'welcome/fa9'
  get 'welcome/fa10'
  get 'welcome/fa11'
  get 'welcome/fa12'
  get 'welcome/fa13'
  get 'welcome/fa14'
  get 'welcome/fa15'
  get 'welcome/fa16'
  get 'welcome/fa17'
  get 'welcome/fa18'
  get 'welcome/fa19'
  get 'welcome/fa20'
  get 'welcome/fa21'
  get 'welcome/fa22'
  get 'welcome/fa23'
  get 'welcome/fa24'
  get 'welcome/fa25'
  get 'welcome/fa26'
  get 'welcome/fa27'
  get 'welcome/fa28'
  get 'welcome/fa29'
  get 'welcome/fa30'
  get 'welcome/fa31'
  get 'welcome/fa32'
  get 'welcome/fa33'
  get 'welcome/fa34'
  get 'welcome/fa35'
  get 'welcome/fa36'
  get 'welcome/fa37'
  get 'welcome/fa38'
  get 'welcome/fa39'
  get 'welcome/fa40'
  get 'welcome/fa41'
  get 'welcome/fa42'
  get 'welcome/fa43'
  get 'welcome/fa44'
  get 'welcome/fa45'
  get 'welcome/fa46'
  get 'welcome/fa47'
  get 'welcome/fa48'
  get 'welcome/fa49'
  get 'welcome/fa50'
  get 'welcome/fa51'
  get 'welcome/fa52'
  get 'welcome/fa53'
  get 'welcome/fa54'
  get 'welcome/fa55'
  get 'welcome/fa56'
  get 'welcome/fa57'
  get 'welcome/fa58'
  get 'welcome/fa59'
  get 'welcome/fa60'












































  get 'welcome/gv1'
  get 'welcome/gv2'
  get 'welcome/gv3'
  get 'welcome/gv4'
  get 'welcome/gv5'
  get 'welcome/gv6'
  get 'welcome/gv7'
  get 'welcome/gv8'
  get 'welcome/gv9'
  get 'welcome/gv10'
  get 'welcome/gv11'
  get 'welcome/gv12'
  get 'welcome/gv13'
  get 'welcome/gv14'
  get 'welcome/gv15'
  get 'welcome/gv16'
  get 'welcome/gv17'
  get 'welcome/gv18'
  get 'welcome/gv19'
  get 'welcome/gv20'
  get 'welcome/gv21'
  get 'welcome/gv22'
  get 'welcome/gv23'
  get 'welcome/gv24'
  get 'welcome/gv25'
  get 'welcome/gv26'
  get 'welcome/gv27'
  get 'welcome/gv28'
  get 'welcome/gv29'
  get 'welcome/gv30'
  get 'welcome/gv31'
  get 'welcome/gv32'
  get 'welcome/gv33'
  get 'welcome/gv34'
  get 'welcome/gv35'
  get 'welcome/gv36'
  get 'welcome/gv37'
  get 'welcome/gv38'
  get 'welcome/gv39'
  get 'welcome/gv40'
  get 'welcome/gv41'
  get 'welcome/gv42'























  get 'welcome/ea1'
  get 'welcome/ea2'
  get 'welcome/ea3'
  get 'welcome/ea4'
  get 'welcome/ea5'
  get 'welcome/ea6'
  get 'welcome/ea7'
  get 'welcome/ea8'
  get 'welcome/ea9'
  get 'welcome/ea10'
  get 'welcome/ea11'
  get 'welcome/ea12'
  get 'welcome/ea13'
  get 'welcome/ea14'
  get 'welcome/ea15'
  get 'welcome/ea16'
  get 'welcome/ea17'
  get 'welcome/ea18'


















  get 'welcome/te1'
  get 'welcome/te2'
  get 'welcome/te3'
  get 'welcome/te4'
  get 'welcome/te5'
  get 'welcome/te6'
  get 'welcome/te7'
  get 'welcome/te8'























  get 'welcome/do1'
  get 'welcome/do2'
  get 'welcome/do3'
  get 'welcome/do4'
  get 'welcome/do5'
  get 'welcome/do6'
  get 'welcome/do7'
  get 'welcome/do8'
  get 'welcome/do9'
  get 'welcome/do10'
  get 'welcome/do11'






















  get 'welcome/bt1'
  get 'welcome/bt2'
  get 'welcome/bt3'
  get 'welcome/bt4'
  get 'welcome/bt5'
  get 'welcome/bt6'

















  get 'welcome/sa1'
  get 'welcome/sa2'
  get 'welcome/sa3'
  get 'welcome/sa4'
  get 'welcome/sa5'





















  get 'welcome/hsr1'
  get 'welcome/hsr2'
  get 'welcome/hsr3'
  get 'welcome/hsr4'
  get 'welcome/hsr5'
  get 'welcome/hsr6'
  get 'welcome/hsr7'
  get 'welcome/hsr8'
  get 'welcome/hsr9'
  get 'welcome/hsr10'
  get 'welcome/hsr11'













  get 'welcome/ren1'
  get 'welcome/ren2'
  get 'welcome/ren3'
  get 'welcome/ren4'
  get 'welcome/ren5'
























  get 'welcome/hard1'
  get 'welcome/hard2'
  get 'welcome/hard3'
  get 'welcome/hard4'
  get 'welcome/hard5'
  get 'welcome/hard6'
  get 'welcome/hard7'
  get 'welcome/hard8'
  get 'welcome/hard9'
  get 'welcome/hard10'
  get 'welcome/hard11'
  get 'welcome/hard12'
  get 'welcome/hard13'
  get 'welcome/hard14'




















  get 'welcome/wed1'
  get 'welcome/wed2'
  get 'welcome/wed3'
  get 'welcome/wed4'
  get 'welcome/wed5'
  get 'welcome/wed6'
  get 'welcome/wed7'
  get 'welcome/wed8'
  get 'welcome/wed9'
  get 'welcome/wed10'
  get 'welcome/wed11'
  get 'welcome/wed12'
  get 'welcome/wed13'
  get 'welcome/wed14'
  get 'welcome/wed15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # new routes
  resources :registeration_numbers do
    resources :orders, controller: 'registeration_numbers/orders'
  end
  post :get_cities_by_state,       action: :get_cities_by_state, controller: :products
  post :get_areas_by_city,       action: :get_areas_by_city, controller: :products

   get "/users/auth/facebook", to: "users#sign_in"
   get "/users/auth/twitter", to: "users#sign_in"
   get "/users/auth/google_oauth2", to: "users#sign_in"
   devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" , sessions: "users/sessions"}

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, class_name: 'OrderItem'
	has_many :products, through:  :items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = current_cart.order
	end

	def show
		@orders = Order.all
	end

	def create
		@order = current_cart.order
		if @order.update_attributes(order_params.merge(status:'open'))
			session[:cart_token] = nil
			# redirect_to  "/charges/new", locale: {order: @order}
			if params[:order]
            	# redirect_to new_charge_path(:order => params[:order])
            	redirect_to controller: 'charges', action: 'new', first_name: params[:order][:first_name],last_name: params[:order][:last_name],mobile_number: params[:order][:mobile_number],email: params[:order][:email],delivery_address: params[:order][:delivery_address],city: params[:order][:city],pincode: params[:order][:pincode],tracking: params[:order][:tracking], amount: params[:paid_amount][:amount], order_id: @order.id
        	end
		else
			render:new
		end
	end

	private
	def order_params
		params.require(:order).permit(:first_name, :las_name, :city, :mobile_number, :delivery_address, :email, :pincode, :tracking)
	end

end

app/controllers/registeration_numbers/orders_controller.rb
class RegisterationNumbers::OrdersController < RegisterationNumbersController
	before_action :check_rn_belongs_to_right_agent

	def index
		@shops = @rn.shops
	end

	private
	def check_rn_belongs_to_right_agent
		@rn = RegisterationNumber.includes([:shops => [:products => [:items]]]).find(params[:registeration_number_id])
		redirect_to "/" if !(current_user && @rn.user.id  == current_user.id)
	end
end

app/helpers/registeration_numbers/orders_helper.rb
module RegisterationNumbers::OrdersHelper
end

app/views/orders/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/assets/checkout.css">
    <title>Check Out</title>
  </head>
  <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding-top:100px; position:relative;">
                
              
                <div>
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                                <i class="fa fa-cart-arrow-down d-block" aria-hidden="true"></i>
                        <p><span class="text-color" style="position:relative;">Cart ------------ Delivery &amp; Billing Address ------------ </span>
                         Payment</p>
                    </li>
                  
                  </ul>
                  
                </div>
              </nav>

        <div class="container mt-5">
            <div class="row">
                <div class="col col-md-8">
                    <div class="order-summary">
                            <div id="accordion">
                                    <div class="card mb-1">
                                      <div class="card-header" id="summary">
                                        <h5 class="mb-0">
                                          <button class="btn" data-toggle="collapse" data-target="#one" aria-expanded="true" aria-controls="one">
                                                <strong>Need Help?</strong>
                                                <span>(<%= link_to pluralize(current_cart.items_count, 'item'), cart_path %>)</span>
                                          </button>
                                        </h5>
                                      </div>
                                  
                                      <div id="one" class="collapse" aria-labelledby="summary" data-parent="#accordion">
                                        <div class="card-body">
                                              <div class="container">
                                                  <div class="col col-md-8">
                                                    <div class="box"> 
                                                        <div class="row">
                                                                <div class="col-md-5">
                                                                    <img src="/assets/help.png" alt="" class="img-fluid">
                                                                </div>
                                                                <div class="col col-md-7">
                                                                    <ul>
                                                                        <li>Need Help With Delivery.</li>
                                                                        <li>If you need any help regarding delivery.</li>
                                                                        <li><span class="text-color"><a href="/welcome/contact">Contact Us</a></span></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                    </div>

                                                  </div>
                                              </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                    </div>

                    <div class="form-checkOut">
                            <div id="accordion">
                                    <div class="card">
                                      <div class="card-header" id="form-checkOut">
                                        <h5 class="mb-0">
                                          <button class="btn" data-toggle="collapse" data-target="#two" aria-expanded="true" aria-controls="two">
                                                <strong class="text-uppercase">Shipping &amp; Billing Details</strong>
                                          </button>
                                        </h5>
                                      </div>
                                  
                                      <div id="two" class="collapse show" aria-labelledby="form-checkOut" data-parent="#accordion">
                                        <div class="card-body">
                                                
                                                  <%= form_for @order, url: checkout_path do |f| %>
                                                        <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          
                                                          <%= f.text_field :first_name, :class => 'lala',  placeholder: "Your First Name" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                         
                                                          <%= f.text_field :last_name, :class => 'lala',  placeholder: "Your Last Name" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                       
                                                          <%= f.text_field :mobile_number, :class => 'lala',  placeholder: "Your Valid Mobile Number", :required => true %>
                                                       
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                     
                                                          <%= f.text_field :email, :class => 'lala',  placeholder: "Your Email Address" %>
                                                      
                                                        </div>
                                                    </div>
                                                        <div class="form-group">
                                                                <div class="d-flex justify-content-between">
                                                        
                                                          <div name="shippingadd">
                                                          <%= f.text_field :delivery_address, :class => 'lala',  placeholder: "Complete Delivery Addresss", name: "shippingadd", :required => true %>
                                                        </div>
                                                      </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                       
                                                          <div name="shippingcity">
                                                          <%= f.text_field :city, :class => 'lala',  placeholder: "Delivery City", name: "shippingcity", :required => true %>
                                                        </div>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                            
                                                          <div name="shippingpin">
                                                          <%= f.text_field :pincode, :class => 'lala',  placeholder: "Pincode", name: "shippingpin", :required => true %>
                                                        </div>
                                                        </div>
                                                    </div>

                                                   

                                                    <div class="trackit" style="display: none;">
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          Tracking
                                                          <%= f.select :tracking, ['Order Checking', 'Order Recived', 'Quality Check', 'Out for delivery', 'Shipment Completed'  ] %>
                                                        </div>
                                                    </div>
                                                  </div>
<input type="hidden" id="paid_amount" name="paid_amount[amount]" value="" />





                                                    

                                                   






                                                            
                                                      
                                        </div>
                                      </div>
                                    </div>
                                    </div>
                                     <div class="mover">
                                                              <%= f.submit "Save & Continue", class: "btn" %>
                                                              </div>
                                                              <% end %>
                    </div>

                </div>
                <div class="col col-md-4">
                    <div class="box">
                        <ul class="d-flex justify-content-between">
                            <li>
                                <p>Item Total</p>
                            </li>
                            <li>
                                <strong>Rs. <%= current_cart.sub_total %></strong>
                            </li>
                        </ul>
                        <ul class="d-flex justify-content-between">
                                <li>
                                    <p>Shipping &amp; Handling <span class="text-color">(free)</span></p>
                                </li>
                                <li>
                                    <strong >Rs. 0</strong>
                                </li>
                            </ul>
                            <hr>
                            <ul class="d-flex justify-content-between">
                                    <li>
                                        <p>You Pay
                                            <br>
                                            <span class="text-muted"><small>(Including all Taxes)</small></span>
                                        </p>
                                    </li>
                                    <li>
                                            <strong id="amount">Rs. <%= current_cart.sub_total %></strong>
                                        </li>
                                </ul>
                    </div>
                </div>
            </div>
        </div>

        <style>
.lala {
    color: #999;
    font-weight: bold;
    font-size: 20px;
    padding: 10px;

    border: 2px solid #999;
    border-radius: 25px;
}
.btn {
    color: #ffffff;
    background-color: #e96a19;
}
.mover {
position: relative;
padding-left: 0px;
padding-bottom: 10px;
}
</style>

<script type="text/javascript">
var amount = $("#amount").text().slice(4, 10);
$("#paid_amount").val(amount);
// alert(amount);
</script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/orders/order_tracking.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact V13</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/assets/util.css">
	<link rel="stylesheet" type="text/css" href="/assets/trako.css">
</head>
<body>


<div class="container-contact100">
	<div class="contact100-map" id="google_map" data-map-x="40.722047" data-map-y="-73.986422" data-pin="/assets/map-marker.png" data-scrollwhell="0" data-draggable="1">
	</div>
	<div class="contact100-more">
		<i class="zmdi zmdi-phone-in-talk"></i>
		 +91 9748 444 800
	</div>
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>The Order number you tried is not associated with any order in our sytem please order something and come back..</p>
  </div>
</div>
<div class="wrap-contact100">
 <form action="/order_tracking" method="get">
	<form class="contact100-form validate-form">
		<span class="contact100-form-title">
			Track Your Order
		</span>

		<div class="wrap-input100 validate-input" data-validate="Number is required">
			<span class="label-input100">Order No.</span>
			<input id="order_number" class="input100" type="text" name="order_number" placeholder="Order Number...">
			<span class="focus-input100"></span>
		</div>
				<div class="container-contact100-form-btn">
			<div class="wrap-contact100-form-btn">
				<div class="contact100-form-bgbtn"></div>
 			    <button type="submit" class="contact100-form-btn" onclick="checkOrderNumber()">Track</button> 
			</div>
		</div>
	</form>
</div>
</div>
<div id="dropDownSelect1"></div>
<div class="home">
</div>

<style>
.container-contact100 {
    background-image: url('/assets/vehicle_tracking_slide1.jpg');
    background-repeat: no-repeat;
    background-size: 50% 100%;
}
</style>
<script src="/assets/trako.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
</body>
</html>

<script type="text/javascript">
function checkOrderNumber(){
	var number=document.getElementById("order_number").value;  
	if (number === undefined || number === null || number == ""){
		alert("Pleae enter Order number.");
	}else{
	}
}
</script>

app/views/orders/show.html.erb
<br>
<br>

<div class="jumbotron text-xs-center">
  <h1 class="display-3">Thank You!</h1>
  <p class="lead"><strong>We Wil contact you</strong> When your order will be dispatched from our seller.</p>
  <hr>
  <p>
    Having trouble? <a href="/welcome/contact">Contact us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="/welcome/home" role="button">Continue to homepage</a>
  </p>
</div>