config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops
  # devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products

  resources :charges

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  get '/cart/tracking', to: 'orders#show', as: :tracking



  
  get 'welcome/home'
  root "welcome#home"
  get 'welcome/rest'
  get 'welcome/old'
  get 'welcome/auto'
  get 'welcome/electronics'
  get 'welcome/fashion'
  get 'welcome/gs'
  get 'welcome/grocery'
  get 'welcome/furniture'
  get 'welcome/health'
  get 'welcome/repair'
  get 'welcome/recent'
  get 'welcome/popular'
  get 'welcome/events'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/search'
  get 'welcome/decor'
  get 'welcome/sny'










  get 'welcome/shop1'
  get 'welcome/shop2'
  get 'welcome/shop3'
  get 'welcome/shop4'
  get 'welcome/shop5'
  get 'welcome/shop6'
  get 'welcome/shop7'
  get 'welcome/shop8'




















  get 'welcome/hbb1'
  get 'welcome/hbb2'
  get 'welcome/hbb3'
  get 'welcome/hbb4'
  get 'welcome/hbb5'
  get 'welcome/hbb6'
  get 'welcome/hbb7'
  get 'welcome/hbb8'
  get 'welcome/hbb9'
  get 'welcome/hbb10'
  get 'welcome/hbb11'
  get 'welcome/hbb12'
  get 'welcome/hbb13'
  get 'welcome/hbb14'
  get 'welcome/hbb15'
  get 'welcome/hbb16'
  get 'welcome/hbb17'
  get 'welcome/hbb18'
  get 'welcome/hbb19'
  get 'welcome/hbb20'
  get 'welcome/hbb21'
  get 'welcome/hbb22'
  get 'welcome/hbb23'
  get 'welcome/hbb24'
  get 'welcome/hbb25'
  get 'welcome/hbb26'
  get 'welcome/hbb27'
  get 'welcome/hbb28'
  get 'welcome/hbb29'
  get 'welcome/hbb30'
  get 'welcome/hbb31'
  get 'welcome/hbb32'
  get 'welcome/hbb33'
  get 'welcome/hbb34'
  get 'welcome/hbb35'
  get 'welcome/hbb36'
  get 'welcome/hbb37'
  get 'welcome/hbb38'
  get 'welcome/hbb39'
  get 'welcome/hbb40'
  get 'welcome/hbb41'
  get 'welcome/hbb42'
  get 'welcome/hbb43'
  get 'welcome/hbb44'
  get 'welcome/hbb45'
  get 'welcome/hbb46'
  get 'welcome/hbb47'
  get 'welcome/hbb48'
  get 'welcome/hbb49'
  get 'welcome/hbb50'
  get 'welcome/hbb51'
  get 'welcome/hbb52'
  get 'welcome/hbb53'
  get 'welcome/hbb54'
  get 'welcome/hbb55'
  get 'welcome/hbb56'
  get 'welcome/hbb57'
  get 'welcome/hbb58'
  get 'welcome/hbb59'
  get 'welcome/hbb60'
  get 'welcome/hbb61'
  get 'welcome/hbb62'
  get 'welcome/hbb63'
  get 'welcome/hbb64'
  get 'welcome/hbb65'
  get 'welcome/hbb66'
  get 'welcome/hbb67'
  get 'welcome/hbb68'
  get 'welcome/hbb69'






























  get 'welcome/fh1'
  get 'welcome/fh2'
  get 'welcome/fh3'
  get 'welcome/fh4'
  get 'welcome/fh5'
  get 'welcome/fh6'
  get 'welcome/fh7'
  get 'welcome/fh8'
  get 'welcome/fh9'
  get 'welcome/fh10'
  get 'welcome/fh11'
  get 'welcome/fh12'
  get 'welcome/fh13'
  get 'welcome/fh14'
  get 'welcome/fh15'
  get 'welcome/fh16'
  get 'welcome/fh17'
  get 'welcome/fh18'
  get 'welcome/fh19'
  get 'welcome/fh20'
  get 'welcome/fh21'
  get 'welcome/fh22'
  get 'welcome/fh23'
  get 'welcome/fh24'
  get 'welcome/fh25'
  get 'welcome/fh26'
  get 'welcome/fh27'
  get 'welcome/fh28'
  get 'welcome/fh29'
  get 'welcome/fh30'
  get 'welcome/fh31'
  get 'welcome/fh32'
  get 'welcome/fh33'
  get 'welcome/fh34'
  get 'welcome/fh35'
  get 'welcome/fh36'
  get 'welcome/fh37'
  get 'welcome/fh38'
  get 'welcome/fh39'
  get 'welcome/fh40'
  get 'welcome/fh41'
  get 'welcome/fh42'
  get 'welcome/fh43'
  get 'welcome/fh44'
  get 'welcome/fh45'
  get 'welcome/fh46'
  get 'welcome/fh47'
  get 'welcome/fh48'
  get 'welcome/fh49'
  get 'welcome/fh50'
  get 'welcome/fh51'
  get 'welcome/fh52'
  get 'welcome/fh53'
  get 'welcome/fh54'
  get 'welcome/fh55'
  get 'welcome/fh56'
  get 'welcome/fh57'
  get 'welcome/fh58'
  get 'welcome/fh59'
  get 'welcome/fh60'
  get 'welcome/fh61'
  get 'welcome/fh62'
  get 'welcome/fh63'
  get 'welcome/fh64'































  get 'welcome/fa1'
  get 'welcome/fa2'
  get 'welcome/fa3'
  get 'welcome/fa4'
  get 'welcome/fa5'
  get 'welcome/fa6'
  get 'welcome/fa7'
  get 'welcome/fa8'
  get 'welcome/fa9'
  get 'welcome/fa10'
  get 'welcome/fa11'
  get 'welcome/fa12'
  get 'welcome/fa13'
  get 'welcome/fa14'
  get 'welcome/fa15'
  get 'welcome/fa16'
  get 'welcome/fa17'
  get 'welcome/fa18'
  get 'welcome/fa19'
  get 'welcome/fa20'
  get 'welcome/fa21'
  get 'welcome/fa22'
  get 'welcome/fa23'
  get 'welcome/fa24'
  get 'welcome/fa25'
  get 'welcome/fa26'
  get 'welcome/fa27'
  get 'welcome/fa28'
  get 'welcome/fa29'
  get 'welcome/fa30'
  get 'welcome/fa31'
  get 'welcome/fa32'
  get 'welcome/fa33'
  get 'welcome/fa34'
  get 'welcome/fa35'
  get 'welcome/fa36'
  get 'welcome/fa37'
  get 'welcome/fa38'
  get 'welcome/fa39'
  get 'welcome/fa40'
  get 'welcome/fa41'
  get 'welcome/fa42'
  get 'welcome/fa43'
  get 'welcome/fa44'
  get 'welcome/fa45'
  get 'welcome/fa46'
  get 'welcome/fa47'
  get 'welcome/fa48'
  get 'welcome/fa49'
  get 'welcome/fa50'
  get 'welcome/fa51'
  get 'welcome/fa52'
  get 'welcome/fa53'
  get 'welcome/fa54'
  get 'welcome/fa55'
  get 'welcome/fa56'
  get 'welcome/fa57'
  get 'welcome/fa58'
  get 'welcome/fa59'
  get 'welcome/fa60'












































  get 'welcome/gv1'
  get 'welcome/gv2'
  get 'welcome/gv3'
  get 'welcome/gv4'
  get 'welcome/gv5'
  get 'welcome/gv6'
  get 'welcome/gv7'
  get 'welcome/gv8'
  get 'welcome/gv9'
  get 'welcome/gv10'
  get 'welcome/gv11'
  get 'welcome/gv12'
  get 'welcome/gv13'
  get 'welcome/gv14'
  get 'welcome/gv15'
  get 'welcome/gv16'
  get 'welcome/gv17'
  get 'welcome/gv18'
  get 'welcome/gv19'
  get 'welcome/gv20'
  get 'welcome/gv21'
  get 'welcome/gv22'
  get 'welcome/gv23'
  get 'welcome/gv24'
  get 'welcome/gv25'
  get 'welcome/gv26'
  get 'welcome/gv27'
  get 'welcome/gv28'
  get 'welcome/gv29'
  get 'welcome/gv30'
  get 'welcome/gv31'
  get 'welcome/gv32'
  get 'welcome/gv33'
  get 'welcome/gv34'
  get 'welcome/gv35'
  get 'welcome/gv36'
  get 'welcome/gv37'
  get 'welcome/gv38'
  get 'welcome/gv39'
  get 'welcome/gv40'
  get 'welcome/gv41'
  get 'welcome/gv42'























  get 'welcome/ea1'
  get 'welcome/ea2'
  get 'welcome/ea3'
  get 'welcome/ea4'
  get 'welcome/ea5'
  get 'welcome/ea6'
  get 'welcome/ea7'
  get 'welcome/ea8'
  get 'welcome/ea9'
  get 'welcome/ea10'
  get 'welcome/ea11'
  get 'welcome/ea12'
  get 'welcome/ea13'
  get 'welcome/ea14'
  get 'welcome/ea15'
  get 'welcome/ea16'
  get 'welcome/ea17'
  get 'welcome/ea18'


















  get 'welcome/te1'
  get 'welcome/te2'
  get 'welcome/te3'
  get 'welcome/te4'
  get 'welcome/te5'
  get 'welcome/te6'
  get 'welcome/te7'
  get 'welcome/te8'























  get 'welcome/do1'
  get 'welcome/do2'
  get 'welcome/do3'
  get 'welcome/do4'
  get 'welcome/do5'
  get 'welcome/do6'
  get 'welcome/do7'
  get 'welcome/do8'
  get 'welcome/do9'
  get 'welcome/do10'
  get 'welcome/do11'






















  get 'welcome/bt1'
  get 'welcome/bt2'
  get 'welcome/bt3'
  get 'welcome/bt4'
  get 'welcome/bt5'
  get 'welcome/bt6'

















  get 'welcome/sa1'
  get 'welcome/sa2'
  get 'welcome/sa3'
  get 'welcome/sa4'
  get 'welcome/sa5'





















  get 'welcome/hsr1'
  get 'welcome/hsr2'
  get 'welcome/hsr3'
  get 'welcome/hsr4'
  get 'welcome/hsr5'
  get 'welcome/hsr6'
  get 'welcome/hsr7'
  get 'welcome/hsr8'
  get 'welcome/hsr9'
  get 'welcome/hsr10'
  get 'welcome/hsr11'













  get 'welcome/ren1'
  get 'welcome/ren2'
  get 'welcome/ren3'
  get 'welcome/ren4'
  get 'welcome/ren5'
























  get 'welcome/hard1'
  get 'welcome/hard2'
  get 'welcome/hard3'
  get 'welcome/hard4'
  get 'welcome/hard5'
  get 'welcome/hard6'
  get 'welcome/hard7'
  get 'welcome/hard8'
  get 'welcome/hard9'
  get 'welcome/hard10'
  get 'welcome/hard11'
  get 'welcome/hard12'
  get 'welcome/hard13'
  get 'welcome/hard14'




















  get 'welcome/wed1'
  get 'welcome/wed2'
  get 'welcome/wed3'
  get 'welcome/wed4'
  get 'welcome/wed5'
  get 'welcome/wed6'
  get 'welcome/wed7'
  get 'welcome/wed8'
  get 'welcome/wed9'
  get 'welcome/wed10'
  get 'welcome/wed11'
  get 'welcome/wed12'
  get 'welcome/wed13'
  get 'welcome/wed14'
  get 'welcome/wed15'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # new routes
  resources :registeration_numbers do
    resources :orders, controller: 'registeration_numbers/orders'
  end
  post :get_cities_by_state,       action: :get_cities_by_state, controller: :products
  post :get_areas_by_city,       action: :get_areas_by_city, controller: :products

   get "/users/auth/facebook", to: "users#sign_in"
   get "/users/auth/twitter", to: "users#sign_in"
   get "/users/auth/google_oauth2", to: "users#sign_in"
   devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" , sessions: "users/sessions"}

end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :imagetwo, ImageUploader
	mount_uploader :imagethree, ImageUploader
	belongs_to :user
	belongs_to :shop
	has_many :items, class_name: 'OrderItem'
	has_many :orders, through:  :items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  skip_before_action :authenticate_user!, only: [:get_cities_by_state, :get_areas_by_city]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.shop.products.build
    
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.shop.products.build(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #get cities from state
  def get_cities_by_state
    @cities = State.find(params[:state]).cities
    respond_to do |format|
      format.json { render :json => @cities }
    end
  end 

  #get area from city
  def get_areas_by_city
    @areas = City.find(params[:city]).areas
    respond_to do |format|
      format.json { render :json => @areas }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image, :imagetwo, :imagethree, :category, :city, :state, :area, :sub_category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<body>
<h2 style="text-align: center;"><b>Editing Listing</b></h2>
<p style="text-align: center;"><b>*You can add products or service that you offer in this form. Businesses like restraunts also come in the service category.</b></p>
<style>
h2{
	color: #fff;
}
p{
	color: #fff;
}
body {
	background-color: #252A33;
}
</style>
<%= render 'form', product: @product %>
</body>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th>Imagetwo</th>
      <th>Imagethree</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= product.image %></td>
        <td><%= product.imagetwo %></td>
        <td><%= product.imagethree %></td>
        <td><%= product.category %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<br>
<br>
<body>
<h2 style="text-align: center;"><b>New Listing</b></h2>
<p style="text-align: center;"><b>*You can add products or service that you offer in this form. Businesses like restraunts also come in the service category.</b></p>
<style>
h2{
	color: #fff;
}
p{
	color: #fff;
}
body {
	background-color: #252A33;
}
</style>
<%= render 'form', product: @product %>
</body>

app/views/products/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= render 'welcome/sub' %>
<br>
<br>
<br>

<body>

  
  <div class="container">
    <div class="card">
      <div class="container-fliud">
        <div class="wrapper row">
          <div class="preview col-md-6">
            
            <div class="preview-pic tab-content">
              <div class="tab-pane active" id="pic-1"><img src="<%= @product.image %>" /></div>
              <div class="tab-pane" id="pic-2"><img src="<%= @product.image %>" /></div>
              <div class="tab-pane" id="pic-3"><img src="<%= @product.imagetwo %>" /></div>
              <div class="tab-pane" id="pic-4"><img src="<%= @product.imagethree %>" /></div>
              
            </div>
            <ul class="preview-thumbnail nav nav-tabs">
              <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="<%= @product.image %>" /></a></li>
              <li><a data-target="#pic-2" data-toggle="tab"><img src="<%= @product.imagetwo %>" /></a></li>
              <li><a data-target="#pic-3" data-toggle="tab"><img src="<%= @product.imagethree %>" /></a></li>
              
            </ul>
            
          </div>
          <div class="details col-md-6">
            <h3 class="product-title"><%= @product.name %></h3>
            <div class="rating">
              <div class="stars">
                <h3>NearClick Certified Product</h3>
              </div>
              
            </div>
            <p class="product-description"><%= @product.description %></p>
            <h4 class="price">current price: <span>Rs: <%= @product.price %></span></h4>
            <p class="vote"><strong>91%</strong> of buyers enjoyed this product!</p>
            <div class="action">
              <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, @product.id %>
       
        <%= number_field_tag :quantity, 1 %>
        <div class="ju" style="padding-top:20px;"></div>
              <button class="add-to-cart btn btn-default" style="padding:10; margin:0;" type="submit">add to cart</button>
              <% end %>
              <!-- <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button> -->
            </div>

            <div class="action">
              <% if current_user == @product.user %>
          <%= link_to "Edit", edit_product_path(@product) %>
          <%= link_to "Delete", @product, method: :delete, data: { confirm: "Do you want to delete this listing ?"}%>
          <% end %>




          
        
        
      
        </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>



<style>

/*****************globals*************/
body {
  font-family: 'open sans';
  overflow-x: hidden;
  background: #eee; }

img {
  max-width: 100%; }

.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  background: #eee;
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  padding: 1.2em 1.5em;
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #85ad00; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

/*# sourceMappingURL=style.css.map */
</style>